test: off
before_build:
  - nuget restore
  - touch ow.Framework/commonsettings.json
  - touch ow.Framework/appsettings.Development.json
  - touch ow.Framework.Tests/appsettings.json
  - touch ow.Service.District/appsettings.json
  - touch ow.Service.Gate/appsettings.json
  - touch ow.Service.Login/appsettings.json
  - touch ow.Utils.GenerateItemsForView/appsettings.json

environment:
  COVERALLS_REPO_TOKEN: 8fQ7xXPq37ZGZxwgKwvhbgXO+g29c7yEgzEwo0UNQkvQNCmh5IpHRmeIBRN+Cm4O
